import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
        <ul>
          <li>
            Home
          </li>
          <li>
            About
          </li>
          <li>
            Contact
          </li>
          <li>
            Blogs
          </li>
        </ul>
      </nav>
    <main className={styles.main}>
        <h1 className={styles.title}>
          Hunting Coder
        </h1>

        <p className={styles.description}>
         A bolg website created using nextjs for developers
        </p>

        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogitem">
             <h3>
               What is the difference between let and const in Javascript?
             </h3>
             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, modi!</p>
             <h3>
               What is the difference between let and const in Javascript?
             </h3>
             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, modi!</p>
             <h3>
               What is the difference between let and const in Javascript?
             </h3>
             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, modi!</p>
             <h3>
               What is the difference between let and const in Javascript?
             </h3>
             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, modi!</p>
          </div>

        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
